import logging

LOGGER = logging.getLogger("snakemake.logging")

if not "REPROFLOW_BASEDIR" in dir():
    # NOTE when used from a module workflow.basedir (and main_snakefile) always point to most-outer wrapping layer, workflow.current_basedir (and snakefile) to the current module
    REPROFLOW_BASEDIR = workflow.current_basedir
LOGGER.info("REPROFLOW_BASEDIR = %s", REPROFLOW_BASEDIR)


configfile: "config.yaml"


include: "rules/create_replicates.smk"


rule all:
    input:
        #"../work/dummy_output.txt",
        #config["replicates"]["output"]
        #expand("{directory}/output_replicates", directory=config["replicates"]["input"])
        expand(
            "output_folder/{sample}_original.bam",
            output_folder=config["alignment"]["output_folder"],
            sample=config["alignment"]["samples"],
        ),


# shell:
# "touch {input}"
